{% set version = "1.4.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-sodium
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sodium_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sodium/sodium_{{ version }}.tar.gz
  sha256: 937d53d5e401f9f7007949e150d7c09c6230fb255c95116b89b5c3237c501acd

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - libsodium >=1.0.3
  run:
    - r-base

test:
  commands:
    - $R -e "library('sodium')"           # [not win]
    - "\"%R%\" -e \"library('sodium')\""  # [win]

about:
  home: https://github.com/jeroen/sodium#readme (devel) https://download.libsodium.org/doc/ (upstream)
  license: MIT
  summary: "Bindings to 'libsodium': a modern, easy-to-use software library for encryption, decryption, signatures, password hashing and more. Sodium uses curve25519, a state-of-the-art Diffie-Hellman function by Daniel Bernstein, which has become very popular after it was discovered that the NSA had backdoored Dual EC DRBG."
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - halldc
