appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: kIQ/1itg8kn6BbrzCw1sw3p2ELpcV8v3N6VDaAfXpl2KaUZu59GcbLXoKWgLU+nCLVOhRPPgj7V1SP7wxa++50EjqYFMSLtqU7br/7PgoRMW9x72gOYy7RuiUOQHVD9iwMlS72gtlKWJBPnYkDU9dlpvWxGgX50M/ZLIzt6DMnFL/0kRv9mEklX2g+SVQQvf4vXQcNOs6UGUOeybiywYorkoiz8ClcpFd5FCluJWlmHhpXo2C/im36JQJhhueX2bac3GN86hAi0Vboc3qjNMEFgumaicqlyBVHM2mhgkai/SuFRq1hXbXpYJdi57xd1UXJsZq543cma7mwQH2Cp75kSry2YHeaZI0APq+jcZNqzWy3QQlkWmAzNDFz1WWzoFurrsjF6gCZnzFhAj8+6Se+mWzKkELsXb62ah62chLoW0AMha/eHH4GuoFIxsK++5uDp2r0EIfd75dQtINdp298Vz+4xNNe/IziFknse/pYnJdtT57O9LuqeYytF+eIhqxk2rnyy0cu+iHcTDOyoYRG+OQoZJ1O6g6xuYDJXeMHNdcn19blhRnj0sMOrxaBT/zoIe3LPOen+aA+i25nVQ9iTSdE4zXpAGGC8jwJxk8TVtDpYnQJ5G5zpPslJMvrzZBIIzPwRruVHnTtMYHBo2ghIMiwzwkaOjdHEc7VcawnU=}
bot:
  automerge: true
